# Generated by Django 2.2.11 on 2020-03-26 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_product_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category_id',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
